<Workspace Version="0.8.2.2392" X="-205.04249084249" Y="248.253266178265" zoom="1.1" Name="View.ViewTemplate" Description="Returns the view template assigned to a given view (if one is assigned)" ID="f2940571-55bf-4cfe-a85b-cf65363b660b" Category="Clockwork.Revit.Views.View.Query">
  <NamespaceResolutionMap>
    <ClassMap partialName="View" resolvedName="Revit.Elements.Views.View" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Function guid="e8f2edca-cf74-4cf1-aa9c-4058f9fd139e" type="Dynamo.Nodes.Function" nickname="Turn Into List" x="459.318181818182" y="202.303994855715" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="cd09ad33-8c34-4850-ac26-24448d92c38f" />
      <Name value="Turn Into List" />
      <Description value="Turns an element (or a nested list) into a flat list" />
      <Inputs>
        <Input value="" />
      </Inputs>
      <Outputs>
        <Output value="seq" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.Symbol guid="4d7090a5-55aa-4d07-aa91-3d027092bbd0" type="Dynamo.Nodes.Symbol" nickname="Input" x="297.954545454545" y="126.931818181818" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="view : View" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="7a99c4da-d79e-4fa4-9b6a-640fdaf8a4a1" type="Dynamo.Nodes.Output" nickname="Output" x="1094.19555444556" y="127.976107226107" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="ViewTemplate" />
    </Dynamo.Nodes.Output>
    <DSIronPythonNode.PythonNode guid="08903bfc-b80a-48fc-9983-cd0487db842e" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="645.038628038627" y="202.497030747031" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="1">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager

doc = DocumentManager.Instance.CurrentDBDocument
views = UnwrapElement(IN[0])
elementlist = list()

for view in views:
	if view.ViewTemplateId.IntegerValue == -1:
		elementlist.append(list())
	else:
		elementlist.append(doc.GetElement(view.ViewTemplateId))
OUT = elementlist</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Function guid="436bfe0a-8565-4b18-9def-41d090d1a5cd" type="Dynamo.Nodes.Function" nickname="ReturnListOrSingleValue" x="851.402264402263" y="127.951576201577" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="44ac4888-4aa4-49a9-9344-23b729c11df9" />
      <Name value="ReturnListOrSingleValue" />
      <Description value="If the item in input #1 is not a list, only the first item of the list in input #2 will be returned." />
      <Inputs>
        <Input value="unknownItem" />
        <Input value="seq" />
      </Inputs>
      <Outputs>
        <Output value="" />
      </Outputs>
    </Dynamo.Nodes.Function>
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="e8f2edca-cf74-4cf1-aa9c-4058f9fd139e" start_index="0" end="08903bfc-b80a-48fc-9983-cd0487db842e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="4d7090a5-55aa-4d07-aa91-3d027092bbd0" start_index="0" end="e8f2edca-cf74-4cf1-aa9c-4058f9fd139e" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="4d7090a5-55aa-4d07-aa91-3d027092bbd0" start_index="0" end="436bfe0a-8565-4b18-9def-41d090d1a5cd" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="08903bfc-b80a-48fc-9983-cd0487db842e" start_index="0" end="436bfe0a-8565-4b18-9def-41d090d1a5cd" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="436bfe0a-8565-4b18-9def-41d090d1a5cd" start_index="0" end="7a99c4da-d79e-4fa4-9b6a-640fdaf8a4a1" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="background_preview" eyeX="10" eyeY="15" eyeZ="10" lookX="-10" lookY="-10" lookZ="-10" />
  </Cameras>
</Workspace>