{
  "Uuid": "576880d2-5f2c-4e34-9183-359361aaa077",
  "IsCustomNode": true,
  "Category": "Clockwork.Geometry.Curves.Create",
  "Description": "Creates a *closed* loop of curves based on a given list of points",
  "Name": "Curve.ClosedLoopThroughPoints",
  "ElementResolver": {
    "ResolutionMap": {
      "PolyCurve": {
        "Key": "Autodesk.DesignScript.Geometry.PolyCurve",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [
    {
      "Id": "d54deaabe6eb4ef1858b8790c179262a",
      "Name": "Boolean",
      "Type": "boolean",
      "Value": "true",
      "Description": "Selection between a true and false."
    }
  ],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "points",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "ce17390f15224ac4b6e69152d83e7a97",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "4a5b25cc8d1f48099a6439233ab12681",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "Curves",
      "Id": "0199b100662e48cbab5cf6a4ed55d5cf",
      "Inputs": [
        {
          "Id": "398688c347b24ab188a4e13eaf832ffc",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.ByPoints@Autodesk.DesignScript.Geometry.Point[],bool",
      "Id": "5392ff8469ed4330a05d385131ee9cd8",
      "Inputs": [
        {
          "Id": "dc21bf1967874d1c97040e199c8e7e55",
          "Name": "points",
          "Description": "Points to make polycurve\n\nPoint[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "874b89d83bf541c6b85b02bfd0073314",
          "Name": "connectLastToFirst",
          "Description": "make close or open polycurve\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "14ec1d8d19fe424b8b69e2dfb7cdef25",
          "Name": "PolyCurve",
          "Description": "PolyCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Make PolyCurve by connecting points. Set the 'connectLastToFirst' input to true to close the PolyCurve.\n\nPolyCurve.ByPoints (points: Point[], connectLastToFirst: bool = false): PolyCurve"
    },
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": true,
      "Id": "d54deaabe6eb4ef1858b8790c179262a",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "babff8d669134e23ae750d8ebf92c58d",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.PolyCurve.Curves",
      "Id": "638b4830596f4c5bad1153164281e348",
      "Inputs": [
        {
          "Id": "e2675e3a75744fd8bc00284a51f26337",
          "Name": "polyCurve",
          "Description": "Autodesk.DesignScript.Geometry.PolyCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1f57fa1030f54df9a034cdf76b7cf233",
          "Name": "Curve[]",
          "Description": "Curve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Returns curves of the polycurve\n\nPolyCurve.Curves ( ): Curve[]"
    }
  ],
  "Connectors": [
    {
      "Start": "4a5b25cc8d1f48099a6439233ab12681",
      "End": "dc21bf1967874d1c97040e199c8e7e55",
      "Id": "b857a5af78ed4620bf54f6766c585b37"
    },
    {
      "Start": "14ec1d8d19fe424b8b69e2dfb7cdef25",
      "End": "e2675e3a75744fd8bc00284a51f26337",
      "Id": "8871f492ad4646b9b9fab622a026f60a"
    },
    {
      "Start": "babff8d669134e23ae750d8ebf92c58d",
      "End": "874b89d83bf541c6b85b02bfd0073314",
      "Id": "82b0a3e307be47c1b5efeb1cefcbfb48"
    },
    {
      "Start": "1f57fa1030f54df9a034cdf76b7cf233",
      "End": "398688c347b24ab188a4e13eaf832ffc",
      "Id": "e6160053a2df45f99030ad141e00f348"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "ce17390f15224ac4b6e69152d83e7a97",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -101.791682947826,
        "Y": 48.5942986496884
      },
      {
        "Id": "0199b100662e48cbab5cf6a4ed55d5cf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 952.208317052174,
        "Y": 77.5942986496884
      },
      {
        "Id": "5392ff8469ed4330a05d385131ee9cd8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "PolyCurve.ByPoints",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 234.208317052174,
        "Y": 77.5942986496884
      },
      {
        "Id": "d54deaabe6eb4ef1858b8790c179262a",
        "IsSetAsInput": true,
        "IsSetAsOutput": false,
        "Name": "Boolean",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -101.791682947826,
        "Y": 132.594298649688
      },
      {
        "Id": "638b4830596f4c5bad1153164281e348",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "PolyCurve.Curves",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 628.208317052174,
        "Y": 77.5942986496884
      }
    ],
    "Annotations": [],
    "X": 87.7872012981285,
    "Y": 440.757094766027,
    "Zoom": 1.17691128698145
  }
}