{
  "Uuid": "c135da75-96f9-404d-9643-3b3d0b998dc1",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.Query",
  "Description": "Returns the design option set of a given design option",
  "Name": "DesignOption.DesignOptionSet",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "designOption",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "fb993e267f3a497eb854118019aae8d3",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "0e786b554bba48268fde033d2efee72d",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "designOptionSet",
      "Id": "b1442ac8b8bf4bb0bba8d890a991e818",
      "Inputs": [
        {
          "Id": "7ef9d27b848644e9b3eeb5d7a1e7e479",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.Elements)\r\n\r\ndef GetDesignOptionSet(item):\r\n\ttry: return item.Document.GetElement(item.get_Parameter(BuiltInParameter.OPTION_SET_ID).AsElementId()).ToDSType(True)\r\n\texcept: return None\r\n\r\nitems = UnwrapElement(IN[0])\r\n\r\nif isinstance(IN[0], list): OUT = [GetDesignOptionSet(x) for x in items]\r\nelse: OUT = GetDesignOptionSet(items)",
      "VariableInputPorts": true,
      "Id": "3ebdfcb3675c48d982ee12926bae512b",
      "Inputs": [
        {
          "Id": "ecc0bfb5a1a74035aa7c95c68d83bc2f",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "51178f206e0c43569573fcb457093c0b",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    }
  ],
  "Connectors": [
    {
      "Start": "0e786b554bba48268fde033d2efee72d",
      "End": "ecc0bfb5a1a74035aa7c95c68d83bc2f",
      "Id": "651928ec5be2494f9bbe10c916249285"
    },
    {
      "Start": "51178f206e0c43569573fcb457093c0b",
      "End": "7ef9d27b848644e9b3eeb5d7a1e7e479",
      "Id": "ab5bead8a1884458b83c256fadf4c65b"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "fb993e267f3a497eb854118019aae8d3",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 231.351071794381,
        "Y": -67.5
      },
      {
        "Id": "b1442ac8b8bf4bb0bba8d890a991e818",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 684.351071794381,
        "Y": -67.5
      },
      {
        "Id": "3ebdfcb3675c48d982ee12926bae512b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Python Script",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 460.351071794381,
        "Y": -67.5
      }
    ],
    "Annotations": [],
    "X": 113.0,
    "Y": 247.0,
    "Zoom": 1.0
  }
}