{
  "Uuid": "61bda511-27e0-4a68-8668-c3ed1c24b62e",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.Actions",
  "Description": "Creates a number of equally spaced vertical intersects for a divided surface based on the path between between two points. You may need to switch start point and end point.",
  "Name": "DividedSurface.VerticalIntersectsByEndpoints",
  "ElementResolver": {
    "ResolutionMap": {
      "Line": {
        "Key": "Autodesk.DesignScript.Geometry.Line",
        "Value": "ProtoGeometry.dll"
      },
      "List": {
        "Key": "DSCore.List",
        "Value": "DSCoreNodes.dll"
      },
      "Vector": {
        "Key": "Autodesk.DesignScript.Geometry.Vector",
        "Value": "ProtoGeometry.dll"
      },
      "ReferencePlane": {
        "Key": "Revit.Elements.ReferencePlane",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      },
      "DividedSurface": {
        "Key": "Revit.Elements.DividedSurface",
        "Value": "RevitNodes.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "dividedSurface",
        "TypeName": "Revit.Elements.DividedSurface",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "de4ee521d19f404690e2749c4add666e",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "0d700b303c884a908fd8aa26d2ce4d0c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "startPoint",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "1b41fe9ccefc4707a8e4dcdb3d8d226c",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "76e6f89ac2944737835c2dc942cea63e",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "endPoint",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "77724451d13545079ba7c5d636637a96",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "8bb735c9740f496490d6b6b99f54245e",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "subdivisions",
        "TypeName": "int",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "953cdc3aa06b4f71a5d930a462134257",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "c3319b2e2a5f4da4ba646f7aed958ab8",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "dividedSurface",
      "Id": "02de61aab9a14c1dbe46e10e9bc97000",
      "Inputs": [
        {
          "Id": "76bcb3170df74a4ba26651ecc9e9c2fb",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "intersects",
      "Id": "1a5794e0884d48cdba01d524fd46214d",
      "Inputs": [
        {
          "Id": "b8ee1721b946467ebf6eabbbadab48da",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "e29fe7ec-cf80-41fd-a1a1-d55b01e15697",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "0108fe09264c46a2aca8f4d5d82e2366",
      "Inputs": [
        {
          "Id": "13d96ff1c9f74225b1a46fe6d9ed0077",
          "Name": "dividedSurface",
          "Description": "DividedSurface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4dba882df88f4d3c8de67996c49876fa",
          "Name": "element",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "927d3f7116ca4fe094d9f914dc65bd28",
          "Name": "dividedSurface",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Adds an intersect to a divided surface"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Subtract@Autodesk.DesignScript.Geometry.Vector",
      "Id": "ad17e8bd13204dbaad00a6bac5352f99",
      "Inputs": [
        {
          "Id": "c83db4e1f7dc46f79927ec4df99fabc3",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "97026c4c16fe4e598debeb4759d20c57",
          "Name": "vectorToSubtract",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "384324e8220c4fba9d75a8ad3fbc4483",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Subtract a vector from a point. The same as Translate(-Vector).\n\nPoint.Subtract (vectorToSubtract: Vector): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter@double",
      "Id": "efedc59ecafc42d48ac059826ab61510",
      "Inputs": [
        {
          "Id": "55748dd02dfe40edb63cdfc28695ff33",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f9d9cb45f8f24c60804f87f98a83ed32",
          "Name": "param",
          "Description": "The parameter at which to evaluate\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a9bcd0d5c74748738c5a60ed85b9abbf",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get a Point on the Curve at a specified parameter between StartParameter() and EndParameter()\n\nCurve.PointAtParameter (param: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.ReferencePlane.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "a5b4099b6e72473b8b6dec4ae688379d",
      "Inputs": [
        {
          "Id": "1eb1a3eaa30445a08032b94728bcd046",
          "Name": "start",
          "Description": "The location where the bubble will be located\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c5ff934943574c59bea662845e16af76",
          "Name": "end",
          "Description": "The other end\n\nPoint",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0082bb12461f414998d518b3f9216875",
          "Name": "ReferencePlane",
          "Description": "ReferencePlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Refernece plane from two end points in the Active view. The cut vector is the Z Axis.\n\nReferencePlane.ByStartPointEndPoint (start: Point, end: Point): ReferencePlane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "43df6cfe-4f8f-42e9-8996-43441bebd19d",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "a6a7a211e68e4d378eafc78cc82e44d4",
      "Inputs": [
        {
          "Id": "672f5a15beaa49fa85241de94e279248",
          "Name": "list",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d0dad53179874cafae976b7b49533d95",
          "Name": "list",
          "Description": "Output #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Drops the last item from a given list."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "3a33a6aa6205440d9cd349ec9dfedc72",
      "Inputs": [
        {
          "Id": "4f6e78c408364c3193a7be864eb43e30",
          "Name": "startPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1f4b64307deb4f7c840fbf53ba75667e",
          "Name": "endPoint",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7bdeba1a068a4f2abedabe28549b4082",
          "Name": "Line",
          "Description": "Line",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a straight Line between two input Points.\n\nLine.ByStartPointEndPoint (startPoint: Point, endPoint: Point): Line"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.RestOfItems@var[]..[]",
      "Id": "6c8eac660c2a4f7c868ea725cf4c6213",
      "Inputs": [
        {
          "Id": "38cad82d88a9496cbd0b6837394a8299",
          "Name": "list",
          "Description": "List to get the rest of.\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "ece7615a7c414e788e784d6f4c88e0f1",
          "Name": "rest",
          "Description": "Rest of the list.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Removes the first item from the given list.\n\nList.RestOfItems (list: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "l / 10;",
      "Id": "27f3d287d90a4e1e890646e6304f8703",
      "Inputs": [
        {
          "Id": "337922e07b2e410fad021b3cabbde63d",
          "Name": "l",
          "Description": "l",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4340bb9fea214894a61d330dfcdb0fe3",
          "Name": "",
          "Description": "Value of expression at line 1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Add@Autodesk.DesignScript.Geometry.Vector",
      "Id": "f5ff068bed22459896c6b73915ccea61",
      "Inputs": [
        {
          "Id": "579e5394ec4d4623b272a9d5904590cd",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "232dbc1b5bb9486e99dbbc570c8076bb",
          "Name": "vectorToAdd",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "8a0840929f314ce3a76a4543a106f496",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Add a vector to a point. The same as Translate(Vector).\n\nPoint.Add (vectorToAdd: Vector): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.Length",
      "Id": "d391df1c98514715a1358a87db5dfc47",
      "Inputs": [
        {
          "Id": "f0ba72a2d7a4469eba3a4160264243de",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "882a7aabba2a4711acd7e333ff51b7c0",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The total arc length of the curve\n\nCurve.Length: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
      "Id": "a24282a204f246a99fcbd24ba49b34c7",
      "Inputs": [
        {
          "Id": "6a69385a89d94b06bfd5f7fa175dd21a",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6d59b21d239f4bd48037e5ef33f8edbe",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "71ace7ec4f894fccb4865bfb7b213730",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point in the XY plane given two 2 cartesian coordinates. The Z component is 0.\n\nPoint.ByCoordinates (x: double = 0, y: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double",
      "Id": "f4d9b10ae9da44f0b561e4e37ea32894",
      "Inputs": [
        {
          "Id": "085a20fd356d4b69bf009e03d2cf797d",
          "Name": "x",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "818a1d6efa034bb6be356bb6985df445",
          "Name": "y",
          "Description": "double\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "06e2d5fe440f4ec48481da489370e6f1",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Point in the XY plane given two 2 cartesian coordinates. The Z component is 0.\n\nPoint.ByCoordinates (x: double = 0, y: double = 0): Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CodeBlockNodeModel, DynamoCore",
      "NodeType": "CodeBlockNode",
      "Code": "seq = 0..1..#(subdiv+1);",
      "Id": "8c8cf82eb2a545b59142f79bc5d0f9cf",
      "Inputs": [
        {
          "Id": "aadea72cfbfa48b095cf795a377d064d",
          "Name": "subdiv",
          "Description": "subdiv",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b7fea724ba764789b1ca454ffeac3a22",
          "Name": "",
          "Description": "seq",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Allows for DesignScript code to be authored directly"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.Scale@double",
      "Id": "2a8db5d0e91f47b09e8fe95ca9d70444",
      "Inputs": [
        {
          "Id": "19dd5d4029ba4649a08b7c91ebb448cd",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3b1f867247a6410da373c4301cb59a9b",
          "Name": "scale_factor",
          "Description": "double\nDefault value : 1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "30a2b236dc724f05acc2e1baf6c2b320",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Scale Vector uniformly around the origin\n\nVector.Scale (scale_factor: double = 1): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "46bf60c3e6cb49d89f41e1e0323ef2de",
      "Inputs": [
        {
          "Id": "ac129308f78845b886e43815b93aeda0",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9123c706268f42eeb62f8c0e0c5976c9",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "3174f4f93b284f6c9c633e68f12466b8",
      "Inputs": [
        {
          "Id": "196ce1e7bc3044488d45cf5dd7a65157",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3311c9e620894801b6e3991b022d1ff3",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.X",
      "Id": "bcc66a5309aa4f80b39ad301dedc66df",
      "Inputs": [
        {
          "Id": "a06899a21d54409f9f9d4bfd37f4ee82",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "1c024f85dd85438a823aef8fd6d50d9c",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the X component of a Point\n\nPoint.X: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Point.Y",
      "Id": "587d26d6a1be438eaba1c0fc72f1f163",
      "Inputs": [
        {
          "Id": "83420c9730d648f385ef1452bb400ceb",
          "Name": "point",
          "Description": "Autodesk.DesignScript.Geometry.Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "55ce7eb2cf34486787b819e1e27e10ce",
          "Name": "double",
          "Description": "double",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the Y component of a Point\n\nPoint.Y: double"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.Cross@Autodesk.DesignScript.Geometry.Vector",
      "Id": "fa45645c3d3246069dc7d2d5eef6d04b",
      "Inputs": [
        {
          "Id": "c043e4c59f6a4f618e0c4d5bb97edd4c",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c265873fa0394adfb1d28df1fa12fb66",
          "Name": "cross",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a6b2897a6c4f448fa25a3f53e58b06a1",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form the cross product of two vectors\n\nVector.Cross (cross: Vector): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ZAxis",
      "Id": "f86831f20ae34770abd1e6c903cf3986",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "6a1f6304a3584798ba48c7672004024d",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the canonical Z axis Vector (0,0,1)\n\nVector.ZAxis ( ): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ByTwoPoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "886a7915a7a54fe0a13e77fe552c5570",
      "Inputs": [
        {
          "Id": "331661d15c2d4d139a665129e63d3bad",
          "Name": "start",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "374d1a0e7cdf4bdbb38ae02bf54d59f9",
          "Name": "end",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2aa2dd6168a7434cbd67eb6468ec700d",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Form a Vector by two end points. The result is a vector from the start to the end point.\n\nVector.ByTwoPoints (start: Point, end: Point): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.Normalized",
      "Id": "274212475d3244d285d84a5ae57d3ce7",
      "Inputs": [
        {
          "Id": "e5dd552acbdf434eafa8e81c60eef5b8",
          "Name": "vector",
          "Description": "Autodesk.DesignScript.Geometry.Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "4f4f2e60b7df44ee888f7f5380779d45",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the normalized version of a vector\n\nVector.Normalized ( ): Vector"
    }
  ],
  "Connectors": [
    {
      "Start": "0d700b303c884a908fd8aa26d2ce4d0c",
      "End": "13d96ff1c9f74225b1a46fe6d9ed0077",
      "Id": "4ab61e232daa41a0bb521772660d26f5"
    },
    {
      "Start": "76e6f89ac2944737835c2dc942cea63e",
      "End": "ac129308f78845b886e43815b93aeda0",
      "Id": "0a645bf6fa2c424ab1efeb76af9c743a"
    },
    {
      "Start": "76e6f89ac2944737835c2dc942cea63e",
      "End": "196ce1e7bc3044488d45cf5dd7a65157",
      "Id": "045ed187747240c49f38b87f5c0b3f76"
    },
    {
      "Start": "8bb735c9740f496490d6b6b99f54245e",
      "End": "a06899a21d54409f9f9d4bfd37f4ee82",
      "Id": "278ca9420455455086b73dd878647e7b"
    },
    {
      "Start": "8bb735c9740f496490d6b6b99f54245e",
      "End": "83420c9730d648f385ef1452bb400ceb",
      "Id": "2e31ea9e18f646bfa11e0daf059dfbeb"
    },
    {
      "Start": "c3319b2e2a5f4da4ba646f7aed958ab8",
      "End": "aadea72cfbfa48b095cf795a377d064d",
      "Id": "61a118e2107e472ebd49f3e8c4041c2e"
    },
    {
      "Start": "927d3f7116ca4fe094d9f914dc65bd28",
      "End": "76bcb3170df74a4ba26651ecc9e9c2fb",
      "Id": "905947c7f17d4814a4c5c224e4889fc3"
    },
    {
      "Start": "384324e8220c4fba9d75a8ad3fbc4483",
      "End": "c5ff934943574c59bea662845e16af76",
      "Id": "172d68d5f07049fd8ef13b181c1d9799"
    },
    {
      "Start": "a9bcd0d5c74748738c5a60ed85b9abbf",
      "End": "c83db4e1f7dc46f79927ec4df99fabc3",
      "Id": "c7823f790d904dbca1f8af27e4251e88"
    },
    {
      "Start": "a9bcd0d5c74748738c5a60ed85b9abbf",
      "End": "579e5394ec4d4623b272a9d5904590cd",
      "Id": "fe32eed96f7647b4b4bd6f2691f62c94"
    },
    {
      "Start": "0082bb12461f414998d518b3f9216875",
      "End": "4dba882df88f4d3c8de67996c49876fa",
      "Id": "085a9de4601644c5a9b0669afe4cd844"
    },
    {
      "Start": "0082bb12461f414998d518b3f9216875",
      "End": "b8ee1721b946467ebf6eabbbadab48da",
      "Id": "7bd9bec10a3d4d56bc2760716ab20d49"
    },
    {
      "Start": "d0dad53179874cafae976b7b49533d95",
      "End": "f9d9cb45f8f24c60804f87f98a83ed32",
      "Id": "5e410644573040b7b890f5296265ec84"
    },
    {
      "Start": "7bdeba1a068a4f2abedabe28549b4082",
      "End": "55748dd02dfe40edb63cdfc28695ff33",
      "Id": "4b1b82399878452caba1e13c0a596a66"
    },
    {
      "Start": "7bdeba1a068a4f2abedabe28549b4082",
      "End": "f0ba72a2d7a4469eba3a4160264243de",
      "Id": "58c73ce3b5a64b6ab946379778c438b5"
    },
    {
      "Start": "ece7615a7c414e788e784d6f4c88e0f1",
      "End": "672f5a15beaa49fa85241de94e279248",
      "Id": "85175b55396a4e0aa5b0a31e122b0591"
    },
    {
      "Start": "4340bb9fea214894a61d330dfcdb0fe3",
      "End": "3b1f867247a6410da373c4301cb59a9b",
      "Id": "560d83bc7a4e4a25b75fafff364959a0"
    },
    {
      "Start": "8a0840929f314ce3a76a4543a106f496",
      "End": "1eb1a3eaa30445a08032b94728bcd046",
      "Id": "be8b0727d04b407da06c253aa1f0d5e0"
    },
    {
      "Start": "882a7aabba2a4711acd7e333ff51b7c0",
      "End": "337922e07b2e410fad021b3cabbde63d",
      "Id": "5e029808918c41118c65c1bcb75fc84d"
    },
    {
      "Start": "71ace7ec4f894fccb4865bfb7b213730",
      "End": "1f4b64307deb4f7c840fbf53ba75667e",
      "Id": "9515cf3a6dad44858870fbc34133d34a"
    },
    {
      "Start": "71ace7ec4f894fccb4865bfb7b213730",
      "End": "374d1a0e7cdf4bdbb38ae02bf54d59f9",
      "Id": "fea79ac49482492ea17cfd7fac839c31"
    },
    {
      "Start": "06e2d5fe440f4ec48481da489370e6f1",
      "End": "4f6e78c408364c3193a7be864eb43e30",
      "Id": "2d0933c587c841f982ca2e5f83d75a11"
    },
    {
      "Start": "06e2d5fe440f4ec48481da489370e6f1",
      "End": "331661d15c2d4d139a665129e63d3bad",
      "Id": "948fc89184974961af468ee12e84da2b"
    },
    {
      "Start": "b7fea724ba764789b1ca454ffeac3a22",
      "End": "38cad82d88a9496cbd0b6837394a8299",
      "Id": "9df94fc083334e2694d35d00f92a31fe"
    },
    {
      "Start": "30a2b236dc724f05acc2e1baf6c2b320",
      "End": "97026c4c16fe4e598debeb4759d20c57",
      "Id": "a22833feafe5410794e35fc291307505"
    },
    {
      "Start": "30a2b236dc724f05acc2e1baf6c2b320",
      "End": "232dbc1b5bb9486e99dbbc570c8076bb",
      "Id": "981b684268c8475a83e71bd3c7626812"
    },
    {
      "Start": "9123c706268f42eeb62f8c0e0c5976c9",
      "End": "085a20fd356d4b69bf009e03d2cf797d",
      "Id": "247e78f3909e4e189232e91e20b0e444"
    },
    {
      "Start": "3311c9e620894801b6e3991b022d1ff3",
      "End": "818a1d6efa034bb6be356bb6985df445",
      "Id": "082b353835ca4823a5d670c787c6cc0b"
    },
    {
      "Start": "1c024f85dd85438a823aef8fd6d50d9c",
      "End": "6a69385a89d94b06bfd5f7fa175dd21a",
      "Id": "3ff98af5352f4170987c941a434eecd2"
    },
    {
      "Start": "55ce7eb2cf34486787b819e1e27e10ce",
      "End": "6d59b21d239f4bd48037e5ef33f8edbe",
      "Id": "f8c96639f0884623b8e967c36bc95117"
    },
    {
      "Start": "a6b2897a6c4f448fa25a3f53e58b06a1",
      "End": "19dd5d4029ba4649a08b7c91ebb448cd",
      "Id": "9f0ed2922dc548a2a797f2495c415c80"
    },
    {
      "Start": "6a1f6304a3584798ba48c7672004024d",
      "End": "c265873fa0394adfb1d28df1fa12fb66",
      "Id": "6c4f69fb7f1640b2a2234a4826aff30b"
    },
    {
      "Start": "2aa2dd6168a7434cbd67eb6468ec700d",
      "End": "e5dd552acbdf434eafa8e81c60eef5b8",
      "Id": "c561f75d8aa0408d911c728a183df5f3"
    },
    {
      "Start": "4f4f2e60b7df44ee888f7f5380779d45",
      "End": "c043e4c59f6a4f618e0c4d5bb97edd4c",
      "Id": "c1ae050598c5403199cf96e0f81f567e"
    }
  ],
  "Dependencies": [
    "e29fe7ec-cf80-41fd-a1a1-d55b01e15697",
    "43df6cfe-4f8f-42e9-8996-43441bebd19d"
  ],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "de4ee521d19f404690e2749c4add666e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2516.73420146273,
        "Y": 747.659473921598
      },
      {
        "Id": "1b41fe9ccefc4707a8e4dcdb3d8d226c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 244.464462622218,
        "Y": 769.081060390292
      },
      {
        "Id": "77724451d13545079ba7c5d636637a96",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 261.357734655702,
        "Y": 976.999770205692
      },
      {
        "Id": "953cdc3aa06b4f71a5d930a462134257",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 329.806631426539,
        "Y": 1127.80573943683
      },
      {
        "Id": "02de61aab9a14c1dbe46e10e9bc97000",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 3204.63798044189,
        "Y": 783.054429472428
      },
      {
        "Id": "1a5794e0884d48cdba01d524fd46214d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2863.95579363812,
        "Y": 900.760634006694
      },
      {
        "Id": "0108fe09264c46a2aca8f4d5d82e2366",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "DividedSurface.AddIntersect",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2860.63798044189,
        "Y": 783.054429472428
      },
      {
        "Id": "ad17e8bd13204dbaad00a6bac5352f99",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Subtract",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2238.13039053537,
        "Y": 950.656631288819
      },
      {
        "Id": "efedc59ecafc42d48ac059826ab61510",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.PointAtParameter",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1313.82569884669,
        "Y": 969.329453343135
      },
      {
        "Id": "a5b4099b6e72473b8b6dec4ae688379d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "ReferencePlane.ByStartPointEndPoint",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2543.11981742253,
        "Y": 872.853206062499
      },
      {
        "Id": "a6a7a211e68e4d378eafc78cc82e44d4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.DropLastItem",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1130.20961531258,
        "Y": 1124.93630379577
      },
      {
        "Id": "3a33a6aa6205440d9cd349ec9dfedc72",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Line.ByStartPointEndPoint",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1035.28943653647,
        "Y": 841.731835971972
      },
      {
        "Id": "6c8eac660c2a4f7c868ea725cf4c6213",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "List.RestOfItems",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 927.920709724151,
        "Y": 1124.93630379577
      },
      {
        "Id": "27f3d287d90a4e1e890646e6304f8703",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1794.26842282271,
        "Y": 838.717823436201
      },
      {
        "Id": "f5ff068bed22459896c6b73915ccea61",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Add",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 2250.57893857158,
        "Y": 812.166534385971
      },
      {
        "Id": "d391df1c98514715a1358a87db5dfc47",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Curve.Length",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1541.01170050755,
        "Y": 835.507561953866
      },
      {
        "Id": "a24282a204f246a99fcbd24ba49b34c7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 824.272310404881,
        "Y": 953.539877739028
      },
      {
        "Id": "f4d9b10ae9da44f0b561e4e37ea32894",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.ByCoordinates",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 809.65950338015,
        "Y": 745.255588691336
      },
      {
        "Id": "8c8cf82eb2a545b59142f79bc5d0f9cf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Code Block",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 589.478847218611,
        "Y": 1130.61953604936
      },
      {
        "Id": "2a8db5d0e91f47b09e8fe95ca9d70444",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.Scale",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1950.25771719798,
        "Y": 732.807040655125
      },
      {
        "Id": "46bf60c3e6cb49d89f41e1e0323ef2de",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.X",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 566.912816674031,
        "Y": 715.690287105335
      },
      {
        "Id": "3174f4f93b284f6c9c633e68f12466b8",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Y",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 571.581022187611,
        "Y": 812.166534385971
      },
      {
        "Id": "bcc66a5309aa4f80b39ad301dedc66df",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.X",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 581.525623698761,
        "Y": 923.974576153027
      },
      {
        "Id": "587d26d6a1be438eaba1c0fc72f1f163",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Point.Y",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 586.19382921234,
        "Y": 1020.45082343366
      },
      {
        "Id": "fa45645c3d3246069dc7d2d5eef6d04b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.Cross",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1696.61855096018,
        "Y": 673.676437483123
      },
      {
        "Id": "f86831f20ae34770abd1e6c903cf3986",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.ZAxis",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1539.45563200302,
        "Y": 745.255588691336
      },
      {
        "Id": "886a7915a7a54fe0a13e77fe552c5570",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.ByTwoPoints",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1184.672012971,
        "Y": 655.003615428806
      },
      {
        "Id": "274212475d3244d285d84a5ae57d3ce7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vector.Normalized",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1435.19904219975,
        "Y": 653.44754692428
      }
    ],
    "Annotations": [
      {
        "Id": "6abf71ff68e44d498eb0ae7afa766081",
        "Title": "Create points for subdivisions",
        "Nodes": [],
        "Left": 1319.84416500964,
        "Top": 930.999967127083,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "2df5e1765c964fb688e77080632d4413",
        "Title": "Create a set of orthogonal planes to curve 1",
        "Nodes": [],
        "Left": 2542.91400956738,
        "Top": 826.743377323815,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "8ea3312034dd466aa9d60756df99e6db",
        "Title": "Project the points to the XY plane and create a line between them",
        "Nodes": [],
        "Left": 1030.41542316774,
        "Top": 784.729527701603,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      },
      {
        "Id": "0c392a93f39f4926ac183b3556d35bae",
        "Title": "Find vector orthogonal to line",
        "Nodes": [],
        "Left": 1973.39293691072,
        "Top": 685.141143411915,
        "Width": 0.0,
        "Height": 0.0,
        "FontSize": 36.0,
        "InitialTop": 0.0,
        "InitialHeight": 0.0,
        "TextblockHeight": 0.0,
        "Background": "#FFC1D676"
      }
    ],
    "X": -56.2362704247676,
    "Y": 15.7814471837413,
    "Zoom": 0.615937071974734
  }
}