{
  "Uuid": "69d63a69-1abb-4e37-82d5-a858db67dfeb",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.Actions",
  "Description": "Moves a point-based element to the given location",
  "Name": "Element.MoveToPoint",
  "ElementResolver": {
    "ResolutionMap": {
      "Point": {
        "Key": "Autodesk.DesignScript.Geometry.Point",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "element",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "9169595ce402425cbaf49c65b4e3b943",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "3d5e8076a11f49b2900401aa3e4f1a64",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Ein Funktionsparameter zur Verwendung mit benutzerdefinierten Blöcken.\r\n\r\nSie können den Typ und den Vorgabewert für den Parameter angeben, z. B.\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "point",
        "TypeName": "Autodesk.DesignScript.Geometry.Point",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "67a978f12bab48cea84a5f4af8a94677",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "e9de3fffca894b9ea12b68c49b3ae7b0",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Ein Funktionsparameter zur Verwendung mit benutzerdefinierten Blöcken.\r\n\r\nSie können den Typ und den Vorgabewert für den Parameter angeben, z. B.\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "element",
      "Id": "0c6a90a2fe0e497a9683ecf6b03b7993",
      "Inputs": [
        {
          "Id": "43f9205d506e425ea62eb681851e1cfd",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "Eine Funktionsausgabe zur Verwendung mit benutzerdefinierten Blöcken"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "success",
      "Id": "b5eb2737365e4d32bc8074eed4ca69f4",
      "Inputs": [
        {
          "Id": "b9d936a5b659403c9271b7e247b70408",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "Eine Funktionsausgabe zur Verwendung mit benutzerdefinierten Blöcken"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vector.ByTwoPoints@Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Point",
      "Id": "3d366be32ab443f1ba1b79f0efe128a7",
      "Inputs": [
        {
          "Id": "83aa2790bfe241e08f56e92781b0707e",
          "Name": "start",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4dcb949db797447884f3f80a43826de7",
          "Name": "end",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2325043731b24c45a64d31903e92f94e",
          "Name": "Vector",
          "Description": "Vector",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Bildet einen Vektor durch zwei Endpunkte. Das Ergebnis ist ein Vektor vom Startpunkt zum Endpunkt.\n\nVector.ByTwoPoints (start: Point, end: Point): Vector"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.Element.GetLocation",
      "Id": "4c019b9da644476fab5123ef94e2965e",
      "Inputs": [
        {
          "Id": "4deeef2e8f5d483fac82565373db6c5d",
          "Name": "element",
          "Description": "Revit.Elements.Element",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f09fbb3bfcda4951bac1a491eeff5b1d",
          "Name": "Geometry",
          "Description": "Geometrie der Position",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Ruft die Position eines bestehenden Elements ab\n\nElement.GetLocation ( ): Geometry"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import sys\r\nimport clr\r\nclr.AddReference('RevitNodes')\r\nclr.AddReference('RevitServices')\r\nfrom RevitServices.Transactions import TransactionManager\r\nfrom RevitServices.Persistence import DocumentManager\r\nimport Revit\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\n\r\nelements = UnwrapElement(IN[0])\r\npoints = UnwrapElement(IN[1])\r\n\r\ndef MoveToPoint(item, point):\r\n\ttry:\r\n\t\tres = item.Location.Move(point.ToXyz(True))\r\n\t\treturn (item, res)\r\n\texcept: return (item, False)\r\n\t\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\nOUT = []\r\nif isinstance(IN[0], list):\r\n\tif isinstance(IN[1], list): results = [MoveToPoint(x, y) for x, y in zip(elements, points)]\r\n\telse: results = [MoveToPoint(x, points) for x in elements]\r\n\tOUT = list(zip(*results))\r\nelse:\r\n\tif isinstance(IN[1], list): OUT = MoveToPoint(elements, points[0])\r\n\telse: OUT = MoveToPoint(elements, points)\r\nTransactionManager.Instance.TransactionTaskDone()",
      "Engine": "CPython3",
      "VariableInputPorts": true,
      "Id": "d1ff0250c1774cbab36878cfdd319a46",
      "Inputs": [
        {
          "Id": "57dc4b91e29d4e37b846a6cb733eb6f3",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0638e2074a62400cbe684c6d2ea5f49a",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "eeb51ee5018249bbb0b3dd527f861a79",
          "Name": "OUT",
          "Description": "Ergebnis des Python-Skripts",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Führt ein eingebettetes Python-Skript aus."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.FirstItem@var[]..[]",
      "Id": "fde24e4742144491b2647db18590bce4",
      "Inputs": [
        {
          "Id": "dcf040a001bb49a994d7ec0897e0de6d",
          "Name": "list",
          "Description": "Liste, deren erstes Element abgerufen werden soll\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2c79f2bb7dd742c087fe2e7eb6c3041e",
          "Name": "item",
          "Description": "Das erste Element in der Liste",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Gibt das erste Element in einer Liste zurück.\n\nList.FirstItem (list: var[]..[]): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DSCore.List.LastItem@var[]..[]",
      "Id": "554e577289814dad99c6fddb685917be",
      "Inputs": [
        {
          "Id": "fe17f664b08042b19ea9ce2bd8620b58",
          "Name": "list",
          "Description": "Liste, deren letztes Element abgerufen werden soll\n\nvar[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2d7e8e0888cf4e7f8235426c96ec2851",
          "Name": "item",
          "Description": "Das letzte Element in der Liste",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Ruft das letzte Element in einer Liste ab.\n\nList.LastItem (list: var[]..[]): var[]..[]"
    }
  ],
  "Connectors": [
    {
      "Start": "3d5e8076a11f49b2900401aa3e4f1a64",
      "End": "4deeef2e8f5d483fac82565373db6c5d",
      "Id": "33e8a5a2ca1643bdb9db549f4d3200f6"
    },
    {
      "Start": "3d5e8076a11f49b2900401aa3e4f1a64",
      "End": "57dc4b91e29d4e37b846a6cb733eb6f3",
      "Id": "cf31f16ede5e43139e4a9f5594bbfdb8"
    },
    {
      "Start": "e9de3fffca894b9ea12b68c49b3ae7b0",
      "End": "4dcb949db797447884f3f80a43826de7",
      "Id": "ada7f15c5175472da2c9246e09bd7f22"
    },
    {
      "Start": "2325043731b24c45a64d31903e92f94e",
      "End": "0638e2074a62400cbe684c6d2ea5f49a",
      "Id": "cf5469e255924e008b667eed1011c10b"
    },
    {
      "Start": "f09fbb3bfcda4951bac1a491eeff5b1d",
      "End": "83aa2790bfe241e08f56e92781b0707e",
      "Id": "453f04b194134da1bb3a610800fa262f"
    },
    {
      "Start": "eeb51ee5018249bbb0b3dd527f861a79",
      "End": "dcf040a001bb49a994d7ec0897e0de6d",
      "Id": "9793f033905c4ab291b7b1cbc2493709"
    },
    {
      "Start": "eeb51ee5018249bbb0b3dd527f861a79",
      "End": "fe17f664b08042b19ea9ce2bd8620b58",
      "Id": "e211ab1ab65d4023bc99f13b31787c8c"
    },
    {
      "Start": "2c79f2bb7dd742c087fe2e7eb6c3041e",
      "End": "43f9205d506e425ea62eb681851e1cfd",
      "Id": "d5f82e200e4f4fb28b994773eb9f7628"
    },
    {
      "Start": "2d7e8e0888cf4e7f8235426c96ec2851",
      "End": "b9d936a5b659403c9271b7e247b70408",
      "Id": "00076ac9949f4e89a50349df6aab24f2"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.1.8246",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Hintergrundvorschau",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "9169595ce402425cbaf49c65b4e3b943",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 112.13230329453359,
        "Y": 453.82158297558237
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "67a978f12bab48cea84a5f4af8a94677",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 412.13230329453359,
        "Y": 554.32158297558237
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "0c6a90a2fe0e497a9683ecf6b03b7993",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1741.7323032945335,
        "Y": 419.32158297558237
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "b5eb2737365e4d32bc8074eed4ca69f4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1741.7323032945335,
        "Y": 503.32158297558237
      },
      {
        "ShowGeometry": true,
        "Name": "Vector.ByTwoPoints",
        "Id": "3d366be32ab443f1ba1b79f0efe128a7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 968.13230329453359,
        "Y": 487.32158297558237
      },
      {
        "ShowGeometry": true,
        "Name": "Element.GetLocation",
        "Id": "4c019b9da644476fab5123ef94e2965e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 412.13230329453359,
        "Y": 446.32158297558237
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "d1ff0250c1774cbab36878cfdd319a46",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1253.7323032945335,
        "Y": 461.32158297558237
      },
      {
        "ShowGeometry": true,
        "Name": "List.FirstItem",
        "Id": "fde24e4742144491b2647db18590bce4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1478.5323032945334,
        "Y": 407.32158297558237
      },
      {
        "ShowGeometry": true,
        "Name": "List.LastItem",
        "Id": "554e577289814dad99c6fddb685917be",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1478.5323032945334,
        "Y": 515.32158297558237
      }
    ],
    "Annotations": [],
    "X": 12.083012250802028,
    "Y": 128.03877030524166,
    "Zoom": 0.36590850270833275
  }
}