{
  "Uuid": "5522a73c-f9bd-45b1-a63b-5c2262fe1f98",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.Query",
  "Description": "Checks if the shape of a roof, floor slab or toposolid has been modified with the shape editing tools",
  "Name": "Element.SlabShapeHasBeenModified",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "element",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "8140bed925774b5784f88195304bdd55",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "44cfa51ddcf14af8b136407820e6813d",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Ein Funktionsparameter zur Verwendung mit benutzerdefinierten Blöcken.\r\n\r\nSie können den Typ und den Vorgabewert für den Parameter angeben, z. B.\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "bool",
      "Id": "4a19ace111264eebbaecf8f1677b06bd",
      "Inputs": [
        {
          "Id": "be8ff006d4a9409c970ed9b272d176e5",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "Eine Funktionsausgabe zur Verwendung mit benutzerdefinierten Blöcken"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\ndef SlabShapeHasBeenModified(item):\r\n\tsle = None\r\n\tif hasattr(item, \"SlabShapeEditor\"): sle = item.SlabShapeEditor\r\n\telif hasattr(item, \"GetSlabShapeEditor\"): sle = item.GetSlabShapeEditor()\r\n\telse: return False\r\n\tif hasattr(sle, \"SlabShapeCreases\") and hasattr(sle, \"SlabShapeVertices\"):\r\n\t\tif sle.SlabShapeCreases.IsEmpty == True or sle.SlabShapeVertices.IsEmpty == True: return False\r\n\t\telse: return True\r\n\telse: return False\r\n\r\nitems = UnwrapElement(IN[0])\r\n\r\nif isinstance(IN[0], list): OUT = [SlabShapeHasBeenModified(x) for x in items]\r\nelse: OUT = SlabShapeHasBeenModified(items)",
      "Engine": "CPython3",
      "VariableInputPorts": true,
      "Id": "705e800a799e46d4959009d28ea5ff0c",
      "Inputs": [
        {
          "Id": "7c29fd2786ba4cefae9a8649ae88a1ae",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f9c08118545e45a59da634d76366d8f6",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Führt ein eingebettetes Python-Skript aus."
    }
  ],
  "Connectors": [
    {
      "Start": "44cfa51ddcf14af8b136407820e6813d",
      "End": "7c29fd2786ba4cefae9a8649ae88a1ae",
      "Id": "e4f132c53cba476a84e21ab4a2af11e6"
    },
    {
      "Start": "f9c08118545e45a59da634d76366d8f6",
      "End": "be8ff006d4a9409c970ed9b272d176e5",
      "Id": "c0e09de2d2454458aa13c4df5a5e496c"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.1.8246",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Hintergrundvorschau",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "8140bed925774b5784f88195304bdd55",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -204.0,
        "Y": 0.0
      },
      {
        "Id": "4a19ace111264eebbaecf8f1677b06bd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 295.0,
        "Y": 0.0
      },
      {
        "Id": "705e800a799e46d4959009d28ea5ff0c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Python Script",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 73.38567594826327,
        "Y": -0.79522531608773761
      }
    ],
    "Annotations": [],
    "X": 276.1044000688243,
    "Y": 267.74116369214875,
    "Zoom": 1.0060041900272454
  }
}