{
  "Uuid": "9de38788-dc20-4d2c-a0e7-ff577538488a",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.Query",
  "Description": "Returns the area property of a given spatial element (room, area or space)",
  "Name": "Element.Area",
  "ElementResolver": {
    "ResolutionMap": {
      "Area": {
        "Key": "DynamoUnits.Area",
        "Value": "DynamoUnits.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "element",
        "TypeName": "var",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "87f38510c9e94c958119d85d995c924f",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "8ae52758efe24c4c9bcf5fdb569b3793",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Ein Funktionsparameter zur Verwendung mit benutzerdefinierten Blöcken.\r\n\r\nSie können den Typ und den Vorgabewert für den Parameter angeben, z. B.\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "area",
      "Id": "8f1bdb124403406c90d67cefe95d4b2d",
      "Inputs": [
        {
          "Id": "a89fc71b3fd848febc6af9ae71697e90",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "Eine Funktionsausgabe zur Verwendung mit benutzerdefinierten Blöcken"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\n\r\nspatialElements = UnwrapElement(IN[0])\r\nversion = IN[1]\r\nif version > 2021: unittype = ForgeTypeId('autodesk.spec.aec:area-2.0.0')\r\nelse: unittype = UnitType.UT_Area\r\n\r\ndef InternalUnitToDisplayUnit(val, unittype):\r\n\tformatoptions = doc.GetUnits().GetFormatOptions(unittype)\r\n\tif version > 2021: dispunits = formatoptions.GetUnitTypeId()\r\n\telse: dispunits = formatoptions.DisplayUnits\r\n\ttry: return UnitUtils.ConvertFromInternalUnits(val,dispunits)\r\n\texcept: return None\r\n\t\r\ndef GetArea(spatialElement):\r\n\tif hasattr(spatialElement, \"Area\"): return InternalUnitToDisplayUnit(spatialElement.Area, unittype)\r\n\telse: return None\r\n\r\nif isinstance(IN[0], list): OUT = [GetArea(x) for x in spatialElements]\r\nelse: OUT = GetArea(spatialElements)",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "a23f1c62848c446994852db3824883ab",
      "Inputs": [
        {
          "Id": "4647ccc5b6894e9182f6823aa4c9bca0",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5b4cf7b4317c4dba8ac2cb99f229790a",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "5e9977d0f667458f889512b91175a699",
          "Name": "OUT",
          "Description": "Ergebnis des Python-Skripts",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Führt ein eingebettetes Python-Skript aus."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "3df0961d-9d46-464f-9175-0a74eeb61bc1",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "898ba93dc1b34f869485aadf120fe784",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "90183e9395654605b033bb500e52dc54",
          "Name": "Name",
          "Description": "Rückgabewert",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "54a8fab092ff44e0b3e8f149f3920748",
          "Name": "Version",
          "Description": "Rückgabewert",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "264c50fffe0d4cd49d7d8463edd69da6",
          "Name": "Build",
          "Description": "Rückgabewert",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9566df7a50754749a94b10e9026fe787",
          "Name": "Language",
          "Description": "Rückgabewert",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "38f19f6618674b91b109412c91d64877",
          "Name": "fullVersion",
          "Description": "Rückgabewert",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Retrieves the name, version and build of the current Revit application."
    }
  ],
  "Connectors": [
    {
      "Start": "8ae52758efe24c4c9bcf5fdb569b3793",
      "End": "4647ccc5b6894e9182f6823aa4c9bca0",
      "Id": "a3b954f8c3b6449f84f51d6093bd943a"
    },
    {
      "Start": "5e9977d0f667458f889512b91175a699",
      "End": "a89fc71b3fd848febc6af9ae71697e90",
      "Id": "345959d3007d4db98f2deec583297945"
    },
    {
      "Start": "54a8fab092ff44e0b3e8f149f3920748",
      "End": "5b4cf7b4317c4dba8ac2cb99f229790a",
      "Id": "ea07f175b77a4f3e8eaa1f05bd590e05"
    }
  ],
  "Dependencies": [
    "3df0961d-9d46-464f-9175-0a74eeb61bc1"
  ],
  "NodeLibraryDependencies": [
    {
      "Name": "Clockwork for Dynamo 2.x",
      "Version": "2.6.0",
      "ReferenceType": "Package",
      "Nodes": [
        "898ba93dc1b34f869485aadf120fe784"
      ]
    }
  ],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.1.8246",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Hintergrundvorschau",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "87f38510c9e94c958119d85d995c924f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 312.08010205918174,
        "Y": 10.056263344522108
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "8f1bdb124403406c90d67cefe95d4b2d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 836.8801020591817,
        "Y": 52.056263344522108
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "a23f1c62848c446994852db3824883ab",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 612.08010205918174,
        "Y": 52.0562633445221
      },
      {
        "ShowGeometry": true,
        "Name": "Application.Version",
        "Id": "898ba93dc1b34f869485aadf120fe784",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 312.08010205918174,
        "Y": 94.056263344522137
      }
    ],
    "Annotations": [],
    "X": 195.095042901716,
    "Y": 381.661599189602,
    "Zoom": 0.73907813570939
  }
}