{
  "Uuid": "31a34783-93cd-4d65-8500-66885bf5a65b",
  "IsCustomNode": true,
  "Category": "Clockwork.Geometry.Abstract.Create",
  "Description": "Creates a plane from face",
  "Name": "Plane.ByBestFitFromFace",
  "ElementResolver": {
    "ResolutionMap": {
      "Plane": {
        "Key": "Autodesk.DesignScript.Geometry.Plane",
        "Value": "ProtoGeometry.dll"
      },
      "Surface": {
        "Key": "Autodesk.DesignScript.Geometry.Surface",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "surface",
        "TypeName": "Autodesk.DesignScript.Geometry.Surface",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "04153f83f5c1412ab148af1dcbe329bd",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7337ee16ce8e44e0b150d86a65d4f210",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "plane",
      "Id": "05b01b23a1f94a05b5d3703a5315cfbf",
      "Inputs": [
        {
          "Id": "6a93881c4f5941d89223ce0b6e251ca8",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Vertex.PointGeometry",
      "Id": "bb3c087d8c2244f08165686c1ff5ef18",
      "Inputs": [
        {
          "Id": "c53a447574164b92bba7536b807cbfa6",
          "Name": "vertex",
          "Description": "Autodesk.DesignScript.Geometry.Vertex",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b490b1bb9aef4917bd15b99a4ffd6cf3",
          "Name": "Point",
          "Description": "Point",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Point where this Vertex is located\n\nVertex.PointGeometry: Point"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Plane.ByBestFitThroughPoints@Autodesk.DesignScript.Geometry.Point[]",
      "Id": "53cf3065571d4c2f8675b46b87e5a4b6",
      "Inputs": [
        {
          "Id": "f0d9a2b6d4d742dbb33719002073a8f9",
          "Name": "points",
          "Description": "Point[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f3a77f71b42143868415a024a98013e9",
          "Name": "Plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Fits a Plane to the input Points; basically a 3D scatterplot fit.\n\nPlane.ByBestFitThroughPoints (points: Point[]): Plane"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Topology.Vertices",
      "Id": "341f8a628b304cb68885876a6afa412a",
      "Inputs": [
        {
          "Id": "d44403bce80c4a12a19e1b03b73c5fc5",
          "Name": "topology",
          "Description": "Autodesk.DesignScript.Geometry.Topology",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f4d9adcc5988424fb5feaf7ca1652823",
          "Name": "Vertex[]",
          "Description": "Vertex[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "The Vertices of the Topology\n\nTopology.Vertices: Vertex[]"
    }
  ],
  "Connectors": [
    {
      "Start": "7337ee16ce8e44e0b150d86a65d4f210",
      "End": "d44403bce80c4a12a19e1b03b73c5fc5",
      "Id": "5f3138aeab5f4a2c8390334f50b5095e"
    },
    {
      "Start": "b490b1bb9aef4917bd15b99a4ffd6cf3",
      "End": "f0d9a2b6d4d742dbb33719002073a8f9",
      "Id": "dc1e12c00503404f9aac5ddbdf7e995b"
    },
    {
      "Start": "f3a77f71b42143868415a024a98013e9",
      "End": "6a93881c4f5941d89223ce0b6e251ca8",
      "Id": "de7a03a7b6294dad94d8ca06e734ee38"
    },
    {
      "Start": "f4d9adcc5988424fb5feaf7ca1652823",
      "End": "c53a447574164b92bba7536b807cbfa6",
      "Id": "3c174550b59c4b6d8f4586ec0bb4f37b"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.1.5055",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "04153f83f5c1412ab148af1dcbe329bd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Input",
        "ShowGeometry": true,
        "Excluded": false,
        "X": -101.829087048831,
        "Y": 1.7674808061538
      },
      {
        "Id": "05b01b23a1f94a05b5d3703a5315cfbf",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Output",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 1076.17091295117,
        "Y": 1.7674808061538
      },
      {
        "Id": "bb3c087d8c2244f08165686c1ff5ef18",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Vertex.PointGeometry",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 488.170912951169,
        "Y": 1.7674808061538
      },
      {
        "Id": "53cf3065571d4c2f8675b46b87e5a4b6",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Plane.ByBestFitThroughPoints",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 777.170912951169,
        "Y": 1.7674808061538
      },
      {
        "Id": "341f8a628b304cb68885876a6afa412a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Topology.Vertices",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 168.170912951169,
        "Y": 1.76748080615381
      }
    ],
    "Annotations": [],
    "X": 301.986626194268,
    "Y": 369.758152808958,
    "Zoom": 1.01250570406626
  }
}