{
  "Uuid": "4d81b7b4-8bc1-4ff8-8fe5-da74bc37fef0",
  "IsCustomNode": true,
  "Category": "Clockwork.Geometry.Solids.Create",
  "Description": "The OOTB node Solid.ByUnion occasionally fails when trying to merge solids with almost adjacent faces. This node will return the minimum amount of joined solids possible in such cases instead of returning null.",
  "Name": "Solid.ByUnion+",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Solid": {
        "Key": "Autodesk.DesignScript.Geometry.Solid",
        "Value": "ProtoGeometry.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\nsolids = IN[0]\r\nOUT = [solids[0]]\r\nsolids = solids[1:]\r\n\r\nfor s in solids:\r\n\ti = 0\r\n\tunionDone = False\r\n\twhile i < len(OUT):\r\n\t\ttry:\r\n\t\t\tOUT[i] = OUT[i].Union(s)\r\n\t\t\tunionDone = True\r\n\t\t\tbreak\r\n\t\texcept:\ti += 1\r\n\tif not unionDone: OUT.append(s)",
      "Engine": "CPython3",
      "VariableInputPorts": true,
      "Id": "72eaf7d655d84984900e9d67d35a5723",
      "Inputs": [
        {
          "Id": "fdde507fb134454ea6a5f248f32485e2",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "a64f928676c74a7e933cf4fb0c10b385",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Führt ein eingebettetes Python-Skript aus."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "solids",
        "TypeName": "Autodesk.DesignScript.Geometry.Solid",
        "TypeRank": 1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "a16037aa5030462984fd8d27bd3e5211",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "61300daf46f5483abfbd3293fa9f4204",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Ein Funktionsparameter zur Verwendung mit benutzerdefinierten Blöcken.\r\n\r\nSie können den Typ und den Vorgabewert für den Parameter angeben, z. B.\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "solids",
      "Id": "5fabc3d5a3f14062ba37c09f42a9bc08",
      "Inputs": [
        {
          "Id": "00383986302f4a5ea3553ad8935a06c6",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "Eine Funktionsausgabe zur Verwendung mit benutzerdefinierten Blöcken"
    }
  ],
  "Connectors": [
    {
      "Start": "a64f928676c74a7e933cf4fb0c10b385",
      "End": "00383986302f4a5ea3553ad8935a06c6",
      "Id": "6290882cabda4257ad7efcedcbd79478"
    },
    {
      "Start": "61300daf46f5483abfbd3293fa9f4204",
      "End": "fdde507fb134454ea6a5f248f32485e2",
      "Id": "26f101040a13406bba62d1da8ed228e1"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.1.8246",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Hintergrundvorschau",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "72eaf7d655d84984900e9d67d35a5723",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 276.5,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "a16037aa5030462984fd8d27bd3e5211",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -51.5,
        "Y": 0.0
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "5fabc3d5a3f14062ba37c09f42a9bc08",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 500.5,
        "Y": 0.0
      }
    ],
    "Annotations": [],
    "X": 212.0,
    "Y": 87.0,
    "Zoom": 1.0
  }
}