{
  "Uuid": "fdc98eeb-e9be-4c20-b9ae-1fa686636067",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.ModelCurve.Create",
  "Description": "Creates area separation lines from geometry curves. ",
  "Name": "AreaSeparator.FromCurve",
  "ElementResolver": {
    "ResolutionMap": {
      "View": {
        "Key": "Revit.Elements.Views.View",
        "Value": "RevitNodes.dll"
      },
      "SketchPlane": {
        "Key": "Revit.Elements.SketchPlane",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "FloorPlanView": {
        "Key": "Revit.Elements.Views.FloorPlanView",
        "Value": "RevitNodes.dll"
      },
      "AreaPlanView": {
        "Key": "Revit.Elements.Views.AreaPlanView",
        "Value": "RevitNodes.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "curve",
        "TypeName": "Autodesk.DesignScript.Geometry.Curve",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "d233a39acfad4a80b0e8859917c5f97f",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7f21f93e3a8a4d2199b5dd555c4b46c2",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Ein Funktionsparameter zur Verwendung mit benutzerdefinierten Blöcken.\r\n\r\nSie können den Typ und den Vorgabewert für den Parameter angeben, z. B.\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "areaSeparator",
      "Id": "1cd26b14cb684c9fb1f275c8db318a86",
      "Inputs": [
        {
          "Id": "e6fd3ec83e4249b99f19a52b2d1a8929",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "Eine Funktionsausgabe zur Verwendung mit benutzerdefinierten Blöcken"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "areaPlan",
        "TypeName": "Revit.Elements.Views.AreaPlanView",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "1692d85850384192880f5db8e03012db",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "fac01ba5085a43ff80bd5c2a20918c69",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Ein Funktionsparameter zur Verwendung mit benutzerdefinierten Blöcken.\r\n\r\nSie können den Typ und den Vorgabewert für den Parameter angeben, z. B.\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\ncurves = UnwrapElement(IN[0])\r\nsketchplane = UnwrapElement(IN[1])\r\nview = UnwrapElement(IN[2])\r\nelementlist = list()\r\n\r\nif str(view.ViewType) == \"AreaPlan\":\r\n\tTransactionManager.Instance.EnsureInTransaction(doc)\r\n\tdoccreation = doc.Create\r\n\tfor curve in curves:\r\n\t\tseparator = doccreation.NewAreaBoundaryLine(sketchplane, curve.ToRevitType(), view)\r\n\t\telementlist.append(separator)\r\n\tTransactionManager.Instance.TransactionTaskDone()\r\nelse:\r\n\telementlist = list(\"The active view needs to be an area plan...\")\r\nOUT = elementlist",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "786d1079e66a4b07a4fde72dbefe5739",
      "Inputs": [
        {
          "Id": "2cb62bca067a415ebd662d8a16359f17",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c9c71176feb648d19634eb3fbbc154c7",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9709aa85540d4d948e69c0324db0b52e",
          "Name": "IN[2]",
          "Description": "Input #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "da655292319c4663812a1638bf0ef08b",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Führt ein eingebettetes Python-Skript aus."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "d6dbde59-f3f7-47b5-9e1e-f30991f58ac1",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "f88b28916c0a4477a478ed04660b258b",
      "Inputs": [
        {
          "Id": "6edb9b0aacf24f33b3f6fab465eb282e",
          "Name": "view",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2b87404274bd43cc8b93cf87c5f7be49",
          "Name": "plane",
          "Description": "Rückgabewert",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Retrieves the plane of a given view"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PullOntoPlane@Autodesk.DesignScript.Geometry.Plane",
      "Id": "1dae20e5d1164566a19b202e6dcd5ef9",
      "Inputs": [
        {
          "Id": "10f3aeb97997416dbe105fb38478d364",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1aa2ec17e9094879b131e7fe09bf429a",
          "Name": "plane",
          "Description": "Die Ebene, in die die Kurve gezogen werden soll\n\nPlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "483164811b9f4fdf8a6ab82ac2a6d05e",
          "Name": "Curve",
          "Description": "Eine Kurve in der Ebene",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Erstellt eine Kurve durch Ziehen in der Ebene.\n\nCurve.PullOntoPlane (plane: Plane): Curve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.SketchPlane.ByPlane@Autodesk.DesignScript.Geometry.Plane",
      "Id": "d2afa6f8f77243d8bb841cc21dc92805",
      "Inputs": [
        {
          "Id": "17c9669e835b452c8237f3073bb46a25",
          "Name": "plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "11a310e178854ccea7c41ba793b199f1",
          "Name": "SketchPlane",
          "Description": "SketchPlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Erstellt eine Revit-SketchPlane anhand einer gegebenen Ebene.\n\nSketchPlane.ByPlane (plane: Plane): SketchPlane"
    }
  ],
  "Connectors": [
    {
      "Start": "7f21f93e3a8a4d2199b5dd555c4b46c2",
      "End": "10f3aeb97997416dbe105fb38478d364",
      "Id": "9e7b764d6b5e4d999baa3ddb3a9c1544"
    },
    {
      "Start": "fac01ba5085a43ff80bd5c2a20918c69",
      "End": "9709aa85540d4d948e69c0324db0b52e",
      "Id": "0f7ff4de77b9443c8cb74a7f6f7cd313"
    },
    {
      "Start": "fac01ba5085a43ff80bd5c2a20918c69",
      "End": "6edb9b0aacf24f33b3f6fab465eb282e",
      "Id": "50e463542bc8492ea7f35410b3e62ada"
    },
    {
      "Start": "da655292319c4663812a1638bf0ef08b",
      "End": "e6fd3ec83e4249b99f19a52b2d1a8929",
      "Id": "3b396d1b58e94bd38fb7b349b8fc5756"
    },
    {
      "Start": "2b87404274bd43cc8b93cf87c5f7be49",
      "End": "1aa2ec17e9094879b131e7fe09bf429a",
      "Id": "2a5b5ce74b9942d9aef3424e12a384b1"
    },
    {
      "Start": "2b87404274bd43cc8b93cf87c5f7be49",
      "End": "17c9669e835b452c8237f3073bb46a25",
      "Id": "8aec3483417a41769c4402dc230f29a8"
    },
    {
      "Start": "483164811b9f4fdf8a6ab82ac2a6d05e",
      "End": "2cb62bca067a415ebd662d8a16359f17",
      "Id": "4c58019970c24fc9ab7afe3bdb53f1c0"
    },
    {
      "Start": "11a310e178854ccea7c41ba793b199f1",
      "End": "c9c71176feb648d19634eb3fbbc154c7",
      "Id": "4abe19f5a78849d891da9a7cdd3a2248"
    }
  ],
  "Dependencies": [
    "d6dbde59-f3f7-47b5-9e1e-f30991f58ac1"
  ],
  "NodeLibraryDependencies": [
    {
      "Name": "Clockwork for Dynamo 2.x",
      "Version": "2.6.0",
      "ReferenceType": "Package",
      "Nodes": [
        "f88b28916c0a4477a478ed04660b258b"
      ]
    }
  ],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.1.8246",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Hintergrundvorschau",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "d233a39acfad4a80b0e8859917c5f97f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -52.0214566576786,
        "Y": -18.7855260152727
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "1cd26b14cb684c9fb1f275c8db318a86",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 947.218705388088,
        "Y": 158.29944664253389
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "1692d85850384192880f5db8e03012db",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": -145.0659799704348,
        "Y": 219.89618690523579
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "786d1079e66a4b07a4fde72dbefe5739",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 741.54461269825265,
        "Y": 158.42982939423092
      },
      {
        "ShowGeometry": true,
        "Name": "View.Plane",
        "Id": "f88b28916c0a4477a478ed04660b258b",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 192.54480876849698,
        "Y": 135.76445237435723
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.PullOntoPlane",
        "Id": "1dae20e5d1164566a19b202e6dcd5ef9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 475.9825032553058,
        "Y": -8.7641529072147932
      },
      {
        "ShowGeometry": true,
        "Name": "SketchPlane.ByPlane",
        "Id": "d2afa6f8f77243d8bb841cc21dc92805",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 457.09319005346487,
        "Y": 134.75881376718493
      }
    ],
    "Annotations": [],
    "X": 226.98227837304967,
    "Y": 155.77630742130387,
    "Zoom": 0.68387381298901562
  }
}