{
  "Uuid": "542e1898-3720-46de-bb65-3892df0cdece",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.ModelCurve.Create",
  "Description": "Creates space separation lines from geometry curves. ",
  "Name": "SpaceSeparator.FromCurve",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "SketchPlane": {
        "Key": "Revit.Elements.SketchPlane",
        "Value": "RevitNodes.dll"
      },
      "View": {
        "Key": "Revit.Elements.Views.View",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.DesignScript.Geometry.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "FloorPlanView": {
        "Key": "Revit.Elements.Views.FloorPlanView",
        "Value": "RevitNodes.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "curve",
        "TypeName": "Autodesk.DesignScript.Geometry.Curve",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "d233a39acfad4a80b0e8859917c5f97f",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "dd5112bcc3f248a68ceb8146635c033f",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Ein Funktionsparameter zur Verwendung mit benutzerdefinierten Blöcken.\r\n\r\nSie können den Typ und den Vorgabewert für den Parameter angeben, z. B.\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "NodeType": "OutputNode",
      "ElementResolver": null,
      "Symbol": "spaceSeparator",
      "Id": "1cd26b14cb684c9fb1f275c8db318a86",
      "Inputs": [
        {
          "Id": "1966f76b582644949c0617e7beda18b0",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "Eine Funktionsausgabe zur Verwendung mit benutzerdefinierten Blöcken"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "NodeType": "InputNode",
      "Parameter": {
        "Name": "floorPlan",
        "TypeName": "Revit.Elements.Views.FloorPlanView",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "1692d85850384192880f5db8e03012db",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "9db621e58de44dc1bbff5cb667d6556c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Ein Funktionsparameter zur Verwendung mit benutzerdefinierten Blöcken.\r\n\r\nSie können den Typ und den Vorgabewert für den Parameter angeben, z. B.\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\ncurves = UnwrapElement(IN[0])\r\nsketchplane = UnwrapElement(IN[1])\r\nview = UnwrapElement(IN[2])\r\n\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\ncurvearray = CurveArray()\r\nfor curve in curves:\r\n\tcurvearray.Append(curve.ToRevitType())\r\ndoccreation = doc.Create\r\nseparatorarray = doccreation.NewSpaceBoundaryLines(sketchplane, curvearray, view)\r\nTransactionManager.Instance.TransactionTaskDone()\r\n\r\nelementlist = list()\r\nfor item in separatorarray:\r\n\telementlist.append(item)\r\nif isinstance(IN[0], list): OUT = elementlist\r\nelse: OUT = elementlist[0]",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "786d1079e66a4b07a4fde72dbefe5739",
      "Inputs": [
        {
          "Id": "363e531992ff45868593e70001ca0785",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "77b03f79e7a245e090b0570e69b3190d",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fa2be151d17245ca948eafe02882c73a",
          "Name": "IN[2]",
          "Description": "Input #2",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "02b905038bdd44c39a1a313182a830a3",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Führt ein eingebettetes Python-Skript aus."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "d6dbde59-f3f7-47b5-9e1e-f30991f58ac1",
      "FunctionType": "Graph",
      "NodeType": "FunctionNode",
      "Id": "4defe1b84c704e99be53ab921a87b216",
      "Inputs": [
        {
          "Id": "07b58b591cce484dba07902f4562bc10",
          "Name": "view",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3db1d7f2dbc0470598cf4c765240a4c5",
          "Name": "plane",
          "Description": "Rückgabewert",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Retrieves the plane of a given view"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PullOntoPlane@Autodesk.DesignScript.Geometry.Plane",
      "Id": "27d885276a4c49748cb028726d3b8c1a",
      "Inputs": [
        {
          "Id": "a2dd710388ee47bb8fac63759313295a",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e8aaf1641a074ff1be35695c50efa568",
          "Name": "plane",
          "Description": "Die Ebene, in die die Kurve gezogen werden soll\n\nPlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "0d79378f6ffb4263b93055c693794b50",
          "Name": "Curve",
          "Description": "Eine Kurve in der Ebene",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Erstellt eine Kurve durch Ziehen in der Ebene.\n\nCurve.PullOntoPlane (plane: Plane): Curve"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Revit.Elements.SketchPlane.ByPlane@Autodesk.DesignScript.Geometry.Plane",
      "Id": "7c3983f1d40447508c86b34e7c4bdbf5",
      "Inputs": [
        {
          "Id": "09d343e01887464b8a70d76957f16b04",
          "Name": "plane",
          "Description": "Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "3281ce27f5074637b710bd5d3fc6c851",
          "Name": "SketchPlane",
          "Description": "SketchPlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Erstellt eine Revit-SketchPlane anhand einer gegebenen Ebene.\n\nSketchPlane.ByPlane (plane: Plane): SketchPlane"
    }
  ],
  "Connectors": [
    {
      "Start": "dd5112bcc3f248a68ceb8146635c033f",
      "End": "a2dd710388ee47bb8fac63759313295a",
      "Id": "b0f3892e129e4eb5aa2ba1a4c5561b35"
    },
    {
      "Start": "9db621e58de44dc1bbff5cb667d6556c",
      "End": "fa2be151d17245ca948eafe02882c73a",
      "Id": "bf787fd9a0654d989a5df1d8038718d1"
    },
    {
      "Start": "9db621e58de44dc1bbff5cb667d6556c",
      "End": "07b58b591cce484dba07902f4562bc10",
      "Id": "ddd2b4f3450a4851b72bc064bd263abd"
    },
    {
      "Start": "02b905038bdd44c39a1a313182a830a3",
      "End": "1966f76b582644949c0617e7beda18b0",
      "Id": "50c577ea50904ca68d7cdb799fd0d940"
    },
    {
      "Start": "3db1d7f2dbc0470598cf4c765240a4c5",
      "End": "e8aaf1641a074ff1be35695c50efa568",
      "Id": "705a965c9ab146868248112eed68ec97"
    },
    {
      "Start": "3db1d7f2dbc0470598cf4c765240a4c5",
      "End": "09d343e01887464b8a70d76957f16b04",
      "Id": "dedca9af6bbe46be9a4896f91961b553"
    },
    {
      "Start": "0d79378f6ffb4263b93055c693794b50",
      "End": "363e531992ff45868593e70001ca0785",
      "Id": "6c251aad0f5e437db4ddc20ad4ed7a15"
    },
    {
      "Start": "3281ce27f5074637b710bd5d3fc6c851",
      "End": "77b03f79e7a245e090b0570e69b3190d",
      "Id": "1d500d52eb1f4043a40e4d729f96f361"
    }
  ],
  "Dependencies": [
    "d6dbde59-f3f7-47b5-9e1e-f30991f58ac1"
  ],
  "NodeLibraryDependencies": [
    {
      "Name": "Clockwork for Dynamo 2.x",
      "Version": "2.6.0",
      "ReferenceType": "Package",
      "Nodes": [
        "4defe1b84c704e99be53ab921a87b216"
      ]
    }
  ],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.12.1.8246",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Hintergrundvorschau",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "d233a39acfad4a80b0e8859917c5f97f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 32.327362695472743,
        "Y": 31.869233501751367
      },
      {
        "ShowGeometry": true,
        "Name": "Output",
        "Id": "1cd26b14cb684c9fb1f275c8db318a86",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1039.5999792775729,
        "Y": 195.84948108677651
      },
      {
        "ShowGeometry": true,
        "Name": "Input",
        "Id": "1692d85850384192880f5db8e03012db",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 26.968143476674811,
        "Y": 251.90400297212136
      },
      {
        "ShowGeometry": true,
        "Name": "Python Script",
        "Id": "786d1079e66a4b07a4fde72dbefe5739",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 840.33300576736,
        "Y": 197.01744721714
      },
      {
        "ShowGeometry": true,
        "Name": "View.Plane",
        "Id": "4defe1b84c704e99be53ab921a87b216",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 322.901490406859,
        "Y": 152.4962243897412
      },
      {
        "ShowGeometry": true,
        "Name": "Curve.PullOntoPlane",
        "Id": "27d885276a4c49748cb028726d3b8c1a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 588.32736269547274,
        "Y": 60.86923350175136
      },
      {
        "ShowGeometry": true,
        "Name": "SketchPlane.ByPlane",
        "Id": "7c3983f1d40447508c86b34e7c4bdbf5",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 552.13420314840278,
        "Y": 196.68307990117637
      }
    ],
    "Annotations": [],
    "X": 121.60479099898691,
    "Y": 166.93184093398264,
    "Zoom": 0.628025679465906
  }
}