{
  "Uuid": "fdc98eeb-e9be-4c20-b9ae-1fa686636067",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.ModelCurve.Create",
  "Description": "Creates area separation lines from geometry curves. ",
  "Name": "AreaSeparator.FromCurve",
  "ElementResolver": {
    "ResolutionMap": {
      "View": {
        "Key": "Revit.Elements.Views.View",
        "Value": "RevitNodes.dll"
      },
      "SketchPlane": {
        "Key": "Revit.Elements.SketchPlane",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "Autodesk.DesignScript.Geometry.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "FloorPlanView": {
        "Key": "Revit.Elements.Views.FloorPlanView",
        "Value": "RevitNodes.dll"
      },
      "AreaPlanView": {
        "Key": "Revit.Elements.Views.AreaPlanView",
        "Value": "RevitNodes.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "Parameter": {
        "Name": "curve",
        "TypeName": "Autodesk.DesignScript.Geometry.Curve",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "d233a39acfad4a80b0e8859917c5f97f",
      "NodeType": "InputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "7f21f93e3a8a4d2199b5dd555c4b46c2",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "ElementResolver": null,
      "Symbol": "areaSeparator",
      "Id": "1cd26b14cb684c9fb1f275c8db318a86",
      "NodeType": "OutputNode",
      "Inputs": [
        {
          "Id": "e6fd3ec83e4249b99f19a52b2d1a8929",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "Parameter": {
        "Name": "areaPlan",
        "TypeName": "Revit.Elements.Views.AreaPlanView",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "1692d85850384192880f5db8e03012db",
      "NodeType": "InputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "fac01ba5085a43ff80bd5c2a20918c69",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\ncurves = UnwrapElement(IN[0])\r\nview = UnwrapElement(IN[1])\r\nelementlist = []\r\n\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\no = view.Origin\r\nn = view.ViewDirection\r\nif o and n: \r\n\tsketchplane = SketchPlane.Create(doc, Plane.CreateByNormalAndOrigin(n, o))\r\n\tdoccreation = doc.Create\r\n\tfor curve in curves:\r\n\t\tseparator = doccreation.NewAreaBoundaryLine(sketchplane, curve.ToRevitType(), view)\r\n\t\telementlist.append(separator)\r\nTransactionManager.Instance.TransactionTaskDone()\r\n\r\nif isinstance(IN[0], list): OUT = elementlist\r\nelse: OUT = elementlist[0]",
      "Engine": "PythonNet3",
      "VariableInputPorts": true,
      "Id": "786d1079e66a4b07a4fde72dbefe5739",
      "NodeType": "PythonScriptNode",
      "Inputs": [
        {
          "Id": "2cb62bca067a415ebd662d8a16359f17",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c9c71176feb648d19634eb3fbbc154c7",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "da655292319c4663812a1638bf0ef08b",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "d6dbde59-f3f7-47b5-9e1e-f30991f58ac1",
      "FunctionType": "Graph",
      "Id": "f88b28916c0a4477a478ed04660b258b",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "6edb9b0aacf24f33b3f6fab465eb282e",
          "Name": "view",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2b87404274bd43cc8b93cf87c5f7be49",
          "Name": "plane",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Retrieves the plane of a given view"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "1dae20e5d1164566a19b202e6dcd5ef9",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "10f3aeb97997416dbe105fb38478d364",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1aa2ec17e9094879b131e7fe09bf429a",
          "Name": "plane",
          "Description": "The plane on which to pull the curve\n\nPlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "483164811b9f4fdf8a6ab82ac2a6d05e",
          "Name": "Curve",
          "Description": "A Curve on the Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PullOntoPlane@Autodesk.DesignScript.Geometry.Plane",
      "Replication": "Auto",
      "Description": "Create a curve by pulling onto plane\n\nCurve.PullOntoPlane (plane: Plane): Curve"
    }
  ],
  "Connectors": [
    {
      "Start": "7f21f93e3a8a4d2199b5dd555c4b46c2",
      "End": "10f3aeb97997416dbe105fb38478d364",
      "Id": "9e7b764d6b5e4d999baa3ddb3a9c1544",
      "IsHidden": "False"
    },
    {
      "Start": "fac01ba5085a43ff80bd5c2a20918c69",
      "End": "6edb9b0aacf24f33b3f6fab465eb282e",
      "Id": "50e463542bc8492ea7f35410b3e62ada",
      "IsHidden": "False"
    },
    {
      "Start": "fac01ba5085a43ff80bd5c2a20918c69",
      "End": "c9c71176feb648d19634eb3fbbc154c7",
      "Id": "43927a26ec7a4ffb9cdb08ea954691f1",
      "IsHidden": "False"
    },
    {
      "Start": "da655292319c4663812a1638bf0ef08b",
      "End": "e6fd3ec83e4249b99f19a52b2d1a8929",
      "Id": "3b396d1b58e94bd38fb7b349b8fc5756",
      "IsHidden": "False"
    },
    {
      "Start": "2b87404274bd43cc8b93cf87c5f7be49",
      "End": "1aa2ec17e9094879b131e7fe09bf429a",
      "Id": "2a5b5ce74b9942d9aef3424e12a384b1",
      "IsHidden": "False"
    },
    {
      "Start": "483164811b9f4fdf8a6ab82ac2a6d05e",
      "End": "2cb62bca067a415ebd662d8a16359f17",
      "Id": "4c58019970c24fc9ab7afe3bdb53f1c0",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [
    "d6dbde59-f3f7-47b5-9e1e-f30991f58ac1"
  ],
  "NodeLibraryDependencies": [
    {
      "Name": "PythonNet3 Engine",
      "Version": "1.1.1",
      "ReferenceType": "Package",
      "Nodes": [
        "786d1079e66a4b07a4fde72dbefe5739"
      ]
    },
    {
      "Name": "Clockwork for Dynamo 2.x",
      "Version": "2.12.0",
      "ReferenceType": "Package",
      "Nodes": [
        "f88b28916c0a4477a478ed04660b258b"
      ]
    }
  ],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "3.6.1.9895",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "d233a39acfad4a80b0e8859917c5f97f",
        "Name": "Input",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 120.27636270882653,
        "Y": 46.62215168947911
      },
      {
        "Id": "1cd26b14cb684c9fb1f275c8db318a86",
        "Name": "Output",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 1188.2763627088266,
        "Y": 75.6221516894791
      },
      {
        "Id": "1692d85850384192880f5db8e03012db",
        "Name": "Input",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -386.12363729117345,
        "Y": 116.12215168947911
      },
      {
        "Id": "786d1079e66a4b07a4fde72dbefe5739",
        "Name": "Python Script",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 963.4763627088266,
        "Y": 75.6221516894791
      },
      {
        "Id": "f88b28916c0a4477a478ed04660b258b",
        "Name": "View.Plane",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 120.27636270882653,
        "Y": 130.6221516894791
      },
      {
        "Id": "1dae20e5d1164566a19b202e6dcd5ef9",
        "Name": "Curve.PullOntoPlane",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 676.2763627088266,
        "Y": 75.62215168947911
      }
    ],
    "Annotations": [],
    "X": -356.1935952216595,
    "Y": 130.0973420327851,
    "Zoom": 0.799595248520623
  }
}