{
  "Uuid": "c68c0799-65c3-42f4-b8ba-93a248013d35",
  "IsCustomNode": true,
  "Category": "Clockwork.Revit.Elements.ModelCurve.Create",
  "Description": "Creates room separation lines from geometry curves. ",
  "Name": "RoomSeparator.FromCurve",
  "ElementResolver": {
    "ResolutionMap": {
      "Autodesk.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "SketchPlane": {
        "Key": "Revit.Elements.SketchPlane",
        "Value": "RevitNodes.dll"
      },
      "View": {
        "Key": "Revit.Elements.Views.View",
        "Value": "RevitNodes.dll"
      },
      "Autodesk.DesignScript.Geometry.Curve": {
        "Key": "Autodesk.DesignScript.Geometry.Curve",
        "Value": "ProtoGeometry.dll"
      },
      "FloorPlanView": {
        "Key": "Revit.Elements.Views.FloorPlanView",
        "Value": "RevitNodes.dll"
      }
    }
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "Parameter": {
        "Name": "curve",
        "TypeName": "Autodesk.DesignScript.Geometry.Curve",
        "TypeRank": -1,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "d233a39acfad4a80b0e8859917c5f97f",
      "NodeType": "InputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "4e98977dd29f443a97a9f9edda9113b4",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Output, DynamoCore",
      "ElementResolver": null,
      "Symbol": "roomSeparator",
      "Id": "1cd26b14cb684c9fb1f275c8db318a86",
      "NodeType": "OutputNode",
      "Inputs": [
        {
          "Id": "05e1304a9fa04efc8751007047e3350e",
          "Name": "",
          "Description": "",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [],
      "Replication": "Disabled",
      "Description": "A function output, use with custom nodes"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Symbol, DynamoCore",
      "Parameter": {
        "Name": "floorPlan",
        "TypeName": "Revit.Elements.Views.FloorPlanView",
        "TypeRank": 0,
        "DefaultValue": null,
        "Description": ""
      },
      "Id": "1692d85850384192880f5db8e03012db",
      "NodeType": "InputNode",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "d92426b538f24446b5a0e9fd7997f24c",
          "Name": "",
          "Description": "Symbol",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "A function parameter, use with custom nodes.\r\n\r\nYou can specify the type and default value for parameter. E.g.,\r\n\r\ninput : var[]..[]\r\nvalue : bool = false"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "Code": "import clr\r\nclr.AddReference('RevitAPI')\r\nfrom Autodesk.Revit.DB import *\r\n\r\nclr.AddReference(\"RevitNodes\")\r\nimport Revit\r\nclr.ImportExtensions(Revit.GeometryConversion)\r\n\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\ndoc = DocumentManager.Instance.CurrentDBDocument\r\ncurves = UnwrapElement(IN[0])\r\nview = UnwrapElement(IN[1])\r\n\r\nTransactionManager.Instance.EnsureInTransaction(doc)\r\no = view.Origin\r\nn = view.ViewDirection\r\nif o and n: \r\n\tsketchplane = SketchPlane.Create(doc, Plane.CreateByNormalAndOrigin(n, o))\r\n\tcurvearray = CurveArray()\r\n\tfor curve in curves:\r\n\t\tcurvearray.Append(curve.ToRevitType())\r\n\tdoccreation = doc.Create\r\n\tseparatorarray = doccreation.NewRoomBoundaryLines(sketchplane, curvearray, view)\r\nelse: separatorarray = []\r\nTransactionManager.Instance.TransactionTaskDone()\r\n\r\nelementlist = list()\r\nfor item in separatorarray:\r\n\telementlist.append(item)\r\nif isinstance(IN[0], list): OUT = elementlist\r\nelse: OUT = elementlist[0]",
      "Engine": "PythonNet3",
      "VariableInputPorts": true,
      "Id": "786d1079e66a4b07a4fde72dbefe5739",
      "NodeType": "PythonScriptNode",
      "Inputs": [
        {
          "Id": "7a0c1849d78e4f06917f8ac6c4594922",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cec85a5f4daa4a6f9209a493e040e117",
          "Name": "IN[1]",
          "Description": "Input #1",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "7f5cc07c3b1a480fae9cb07e3baba6de",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.CustomNodes.Function, DynamoCore",
      "FunctionSignature": "d6dbde59-f3f7-47b5-9e1e-f30991f58ac1",
      "FunctionType": "Graph",
      "Id": "b4fce3f528624c3fa7024e362c08ab5f",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "82b04bbe97474ae58a6e3b933738fcee",
          "Name": "view",
          "Description": "var[]..[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b43606c2653b459f8bd17e068e249c83",
          "Name": "plane",
          "Description": "return value",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Retrieves the plane of a given view"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "Id": "155a8104f33e46e7aad7719300fc6d22",
      "NodeType": "FunctionNode",
      "Inputs": [
        {
          "Id": "9051852b60f64485850549751b4b5259",
          "Name": "curve",
          "Description": "Autodesk.DesignScript.Geometry.Curve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "7de28b8d73de444b93648531f2823408",
          "Name": "plane",
          "Description": "The plane on which to pull the curve\n\nPlane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "bad3f619a98441f4a7da6cd594af753e",
          "Name": "Curve",
          "Description": "A Curve on the Plane",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "FunctionSignature": "Autodesk.DesignScript.Geometry.Curve.PullOntoPlane@Autodesk.DesignScript.Geometry.Plane",
      "Replication": "Auto",
      "Description": "Create a curve by pulling onto plane\n\nCurve.PullOntoPlane (plane: Plane): Curve"
    }
  ],
  "Connectors": [
    {
      "Start": "4e98977dd29f443a97a9f9edda9113b4",
      "End": "9051852b60f64485850549751b4b5259",
      "Id": "44c9f51b369d447b8bc8f84cc7d8a6fb",
      "IsHidden": "False"
    },
    {
      "Start": "d92426b538f24446b5a0e9fd7997f24c",
      "End": "82b04bbe97474ae58a6e3b933738fcee",
      "Id": "2186c2971e3247a2b27797836a7073f4",
      "IsHidden": "False"
    },
    {
      "Start": "d92426b538f24446b5a0e9fd7997f24c",
      "End": "cec85a5f4daa4a6f9209a493e040e117",
      "Id": "7768de3ff3ba457a9cbdc39340bdd2bc",
      "IsHidden": "False"
    },
    {
      "Start": "7f5cc07c3b1a480fae9cb07e3baba6de",
      "End": "05e1304a9fa04efc8751007047e3350e",
      "Id": "a74e4860278c41c583541c884a279cde",
      "IsHidden": "False"
    },
    {
      "Start": "b43606c2653b459f8bd17e068e249c83",
      "End": "7de28b8d73de444b93648531f2823408",
      "Id": "217ac9afdc9e401fbf6f0bdb09f22254",
      "IsHidden": "False"
    },
    {
      "Start": "bad3f619a98441f4a7da6cd594af753e",
      "End": "7a0c1849d78e4f06917f8ac6c4594922",
      "Id": "77bae4272df3484685bc67f30b80a4a1",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [
    "d6dbde59-f3f7-47b5-9e1e-f30991f58ac1"
  ],
  "NodeLibraryDependencies": [
    {
      "Name": "PythonNet3 Engine",
      "Version": "1.1.1",
      "ReferenceType": "Package",
      "Nodes": [
        "786d1079e66a4b07a4fde72dbefe5739"
      ]
    },
    {
      "Name": "Clockwork for Dynamo 2.x",
      "Version": "2.12.0",
      "ReferenceType": "Package",
      "Nodes": [
        "b4fce3f528624c3fa7024e362c08ab5f"
      ]
    }
  ],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "3.6.1.9895",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "_Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Id": "d233a39acfad4a80b0e8859917c5f97f",
        "Name": "Input",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -191.29949729510076,
        "Y": 9.914217599507822
      },
      {
        "Id": "1cd26b14cb684c9fb1f275c8db318a86",
        "Name": "Output",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 876.7005027048992,
        "Y": 38.914217599507815
      },
      {
        "Id": "1692d85850384192880f5db8e03012db",
        "Name": "Input",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -715.2994972951008,
        "Y": 79.41421759950782
      },
      {
        "Id": "786d1079e66a4b07a4fde72dbefe5739",
        "Name": "Python Script",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 650.5958322031329,
        "Y": 38.91421759950782
      },
      {
        "Id": "b4fce3f528624c3fa7024e362c08ab5f",
        "Name": "View.Plane",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": -191.29949729510076,
        "Y": 93.91421759950782
      },
      {
        "Id": "155a8104f33e46e7aad7719300fc6d22",
        "Name": "Curve.PullOntoPlane",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "ShowGeometry": true,
        "X": 364.70050270489924,
        "Y": 38.91421759950782
      }
    ],
    "Annotations": [],
    "X": 252.2603498483088,
    "Y": 119.6967303747745,
    "Zoom": 0.613181641584442
  }
}