<Workspace Version="0.8.3.2580" X="-44.4238387148129" Y="279.661039031388" zoom="0.780539960064318" Name="PerspectiveView.OrientToEyeAndTargetPosition" Description="Sets the orientation of a given perspective view based on a given eye and target position" ID="161bade3-e592-4aff-a1f7-0a49f2f92bab" Category="Clockwork.Revit.Views.PerspectiveView.Actions">
  <NamespaceResolutionMap>
    <ClassMap partialName="Vector" resolvedName="Autodesk.DesignScript.Geometry.Vector" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="Plane" resolvedName="Autodesk.DesignScript.Geometry.Plane" assemblyName="ProtoGeometry.dll" />
    <ClassMap partialName="PerspectiveView" resolvedName="Revit.Elements.Views.PerspectiveView" assemblyName="RevitNodes.dll" />
    <ClassMap partialName="Autodesk.Point" resolvedName="Autodesk.DesignScript.Geometry.Point" assemblyName="ProtoGeometry.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <Dynamo.Nodes.Function guid="0211070c-6bf7-4490-a398-9f05a7517dff" type="Dynamo.Nodes.Function" nickname="Normal.CorrectOrientation" x="819.611393582681" y="246.601658672487" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="2f9c4a7e-aa1d-49da-8132-5fd89adea518" />
      <Name value="Normal.CorrectOrientation" />
      <Description value="Inverts normal A if its inversion is closer to normal B" />
      <Inputs>
        <Input value="VectorA" />
        <Input value="VectorB" />
      </Inputs>
      <Outputs>
        <Output value="Vector" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <DSIronPythonNode.PythonNode guid="d9ec8776-ff01-41cd-a52c-297fb0ebe385" type="DSIronPythonNode.PythonNode" nickname="Python Script" x="1078" y="96.7816666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" inputcount="4">
      <Script>import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
clr.ImportExtensions(Revit.GeometryConversion)

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
view = UnwrapElement(IN[0])
eyeposition = IN[1].ToXyz()
updirection = IN[2].ToXyz()
forwarddirection = IN[3].ToXyz()

TransactionManager.Instance.EnsureInTransaction(doc)
newVO = ViewOrientation3D(eyeposition, updirection, forwarddirection)
view.SetOrientation(newVO)
view.SaveOrientation()
TransactionManager.Instance.TransactionTaskDone()

OUT = view</Script>
    </DSIronPythonNode.PythonNode>
    <Dynamo.Nodes.Symbol guid="06467a3d-689d-4c95-9a25-05bd2cf20268" type="Dynamo.Nodes.Symbol" nickname="Input" x="795.861909470618" y="47.0293255875843" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="view : PerspectiveView" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="0bc4eb96-3476-427e-b1c5-71a8ea04eaf2" type="Dynamo.Nodes.Symbol" nickname="Input" x="-63.9127036494182" y="120.989668572361" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="eyePosition : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Symbol guid="74de2f0e-1a37-462f-a236-939123e6bc9b" type="Dynamo.Nodes.Symbol" nickname="Input" x="-91.3321819086399" y="206.626741207939" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True">
      <Symbol value="targetPosition : Autodesk.Point" />
    </Dynamo.Nodes.Symbol>
    <Dynamo.Nodes.Output guid="91787c15-2230-4d7c-b7da-5c43f9bbd807" type="Dynamo.Nodes.Output" nickname="Output" x="1855" y="46.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <Symbol value="View" />
    </Dynamo.Nodes.Output>
    <Dynamo.Nodes.Function guid="4fed9621-54e6-46d2-a2db-f3f039afa888" type="Dynamo.Nodes.Function" nickname="View3D.IsLocked" x="1078" y="13.2183333333333" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False">
      <ID value="76a987d5-ecf6-4340-a9be-3e992068314b" />
      <Name value="View3D.IsLocked" />
      <Description value="Checks if a given view is locked" />
      <Inputs>
        <Input value="view3d" />
      </Inputs>
      <Outputs>
        <Output value="bool" />
      </Outputs>
    </Dynamo.Nodes.Function>
    <Dynamo.Nodes.CodeBlockNodeModel guid="ebf98918-9104-4811-b4fc-63bc2b4f652d" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1311" y="50.4366666666667" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="islocked ? &quot;The view is locked...&quot; : view;" ShouldFocus="false" />
    <Dynamo.Nodes.CodeBlockNodeModel guid="45470fec-415d-40df-ad29-9435c8c05d83" type="Dynamo.Nodes.CodeBlockNodeModel" nickname="Code Block" x="259.260694792796" y="180.566658672487" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" CodeText="v1 = Vector.ByTwoPoints(epos,tpos).Normalized();&#xA;zvec = Vector.ZAxis();&#xA;p3 = tpos.Add(zvec);&#xA;n = Plane.ByThreePoints(epos,tpos,p3).Normal;&#xA;v1.Rotate(n,90);" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Models.ConnectorModel start="0211070c-6bf7-4490-a398-9f05a7517dff" start_index="0" end="d9ec8776-ff01-41cd-a52c-297fb0ebe385" end_index="2" portType="0" />
    <Dynamo.Models.ConnectorModel start="d9ec8776-ff01-41cd-a52c-297fb0ebe385" start_index="0" end="ebf98918-9104-4811-b4fc-63bc2b4f652d" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="06467a3d-689d-4c95-9a25-05bd2cf20268" start_index="0" end="d9ec8776-ff01-41cd-a52c-297fb0ebe385" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="06467a3d-689d-4c95-9a25-05bd2cf20268" start_index="0" end="4fed9621-54e6-46d2-a2db-f3f039afa888" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="0bc4eb96-3476-427e-b1c5-71a8ea04eaf2" start_index="0" end="d9ec8776-ff01-41cd-a52c-297fb0ebe385" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="0bc4eb96-3476-427e-b1c5-71a8ea04eaf2" start_index="0" end="45470fec-415d-40df-ad29-9435c8c05d83" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="74de2f0e-1a37-462f-a236-939123e6bc9b" start_index="0" end="45470fec-415d-40df-ad29-9435c8c05d83" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="4fed9621-54e6-46d2-a2db-f3f039afa888" start_index="0" end="ebf98918-9104-4811-b4fc-63bc2b4f652d" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="ebf98918-9104-4811-b4fc-63bc2b4f652d" start_index="0" end="91787c15-2230-4d7c-b7da-5c43f9bbd807" end_index="0" portType="0" />
    <Dynamo.Models.ConnectorModel start="45470fec-415d-40df-ad29-9435c8c05d83" start_index="0" end="d9ec8776-ff01-41cd-a52c-297fb0ebe385" end_index="3" portType="0" />
    <Dynamo.Models.ConnectorModel start="45470fec-415d-40df-ad29-9435c8c05d83" start_index="1" end="0211070c-6bf7-4490-a398-9f05a7517dff" end_index="1" portType="0" />
    <Dynamo.Models.ConnectorModel start="45470fec-415d-40df-ad29-9435c8c05d83" start_index="4" end="0211070c-6bf7-4490-a398-9f05a7517dff" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Hintergrundvorschau" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>